### ISSUE TITLE
BeautifulSoup

### ISSUE THREAD

**Issue by jmcurran** [thommiller/Reddit-Image-Scraper#1]
I had to change the first line of `requirements.txt` to `BeautifulSoup4==4.6.0` 
I don't think the version number is as important as the `BeautifulSoup4`

**Comment by thommiller** [comment]
Thanks!!

On 16 Jun 2018 01:06, jmcurran <notifications@github.com> wrote:

I had to change the first line of requirements.txt to BeautifulSoup4==4.6.0
I don't think the version number is as important as the BeautifulSoup4
